//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorDeActividades.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACTIVITY()
        {
            this.TEAM_PROJECT = new HashSet<TEAM_PROJECT>();
        }
    
        public int act_code { get; set; }
        public string act_description { get; set; }
        public Nullable<System.DateTime> act_date_delivery { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAM_PROJECT> TEAM_PROJECT { get; set; }
    }
}
