//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorDeActividades.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GESTOR_DE_ACTIVIDADESEntities : DbContext
    {
        public GESTOR_DE_ACTIVIDADESEntities()
            : base("name=GESTOR_DE_ACTIVIDADESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVITY> ACTIVITY { get; set; }
        public virtual DbSet<PROJECT> PROJECT { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<TEAM_PROJECT> TEAM_PROJECT { get; set; }
        public virtual DbSet<WORKERS> WORKERS { get; set; }
    }
}
