//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorDeActividades.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        public int pro_ncode { get; set; }
        public string pro_name { get; set; }
        public Nullable<System.DateTime> pro_initial_Date { get; set; }
        public Nullable<System.DateTime> pro_final_Date { get; set; }
        public Nullable<int> tpr_ncode { get; set; }
    
        public virtual TEAM_PROJECT TEAM_PROJECT { get; set; }
    }
}
