//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorDeActividades.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORKERS()
        {
            this.TEAM_PROJECT = new HashSet<TEAM_PROJECT>();
        }
    
        public int wok_code { get; set; }
        public string wok_name { get; set; }
        public Nullable<int> rol_code { get; set; }
    
        public virtual ROLES ROLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAM_PROJECT> TEAM_PROJECT { get; set; }
    }
}
